# QFw is inactive unless srun receives --qfw-qpm=service-id[,service-id...].
required /usr/lib64/slurm/spank_qfw.so helper=/opt/openqse/qfw/bin/defw-python directory=slurmctld:18090 directory-name=qfw-site-dirsvc site-config=/etc/openqse/qfw/site.yaml
