# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_job_reservation import V0043JobReservation

class TestV0043JobReservation(unittest.TestCase):
    """V0043JobReservation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043JobReservation:
        """Test V0043JobReservation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043JobReservation`
        """
        model = V0043JobReservation()
        if include_optional:
            return V0043JobReservation(
                id = 56,
                name = '',
                requested = ''
            )
        else:
            return V0043JobReservation(
        )
        """

    def testV0043JobReservation(self):
        """Test V0043JobReservation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
