# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_partition_info_accounts import V0043PartitionInfoAccounts

class TestV0043PartitionInfoAccounts(unittest.TestCase):
    """V0043PartitionInfoAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043PartitionInfoAccounts:
        """Test V0043PartitionInfoAccounts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043PartitionInfoAccounts`
        """
        model = V0043PartitionInfoAccounts()
        if include_optional:
            return V0043PartitionInfoAccounts(
                allowed = '',
                deny = ''
            )
        else:
            return V0043PartitionInfoAccounts(
        )
        """

    def testV0043PartitionInfoAccounts(self):
        """Test V0043PartitionInfoAccounts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
