# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_shares_resp_msg import V0043SharesRespMsg

class TestV0043SharesRespMsg(unittest.TestCase):
    """V0043SharesRespMsg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043SharesRespMsg:
        """Test V0043SharesRespMsg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043SharesRespMsg`
        """
        model = V0043SharesRespMsg()
        if include_optional:
            return V0043SharesRespMsg(
                shares = [
                    openapi_client.models.v0/0/43_assoc_shares_obj_wrap.v0.0.43_assoc_shares_obj_wrap(
                        id = 56, 
                        cluster = '', 
                        name = '', 
                        parent = '', 
                        partition = '', 
                        shares_normalized = openapi_client.models.v0/0/43_float64_no_val_struct.v0.0.43_float64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        shares = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = openapi_client.models.v0_0_43_assoc_shares_obj_wrap_tres.v0_0_43_assoc_shares_obj_wrap_tres(
                            run_seconds = [
                                openapi_client.models.v0/0/43_shares_uint64_tres.v0.0.43_shares_uint64_tres(
                                    name = '', 
                                    value = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                                        set = True, 
                                        infinite = True, 
                                        number = 56, ), )
                                ], 
                            group_minutes = [
                                openapi_client.models.v0/0/43_shares_uint64_tres.v0.0.43_shares_uint64_tres(
                                    name = '', )
                                ], 
                            usage = [
                                openapi_client.models.v0/0/43_shares_float128_tres.v0.0.43_shares_float128_tres(
                                    name = '', )
                                ], ), 
                        effective_usage = openapi_client.models.v0/0/43_float64_no_val_struct.v0.0.43_float64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 1.337, ), 
                        usage_normalized = , 
                        usage = 56, 
                        fairshare = openapi_client.models.v0_0_43_assoc_shares_obj_wrap_fairshare.v0_0_43_assoc_shares_obj_wrap_fairshare(
                            factor = , 
                            level = , ), 
                        type = [
                            'USER'
                            ], )
                    ],
                total_shares = 56
            )
        else:
            return V0043SharesRespMsg(
        )
        """

    def testV0043SharesRespMsg(self):
        """Test V0043SharesRespMsg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
