# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_stats_user import V0043StatsUser

class TestV0043StatsUser(unittest.TestCase):
    """V0043StatsUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StatsUser:
        """Test V0043StatsUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StatsUser`
        """
        model = V0043StatsUser()
        if include_optional:
            return V0043StatsUser(
                user = '',
                count = 56,
                time = openapi_client.models.v0_0_42_stats_rpc_time.v0_0_42_stats_rpc_time(
                    average = 56, 
                    total = 56, )
            )
        else:
            return V0043StatsUser(
        )
        """

    def testV0043StatsUser(self):
        """Test V0043StatsUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
