# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0042_step_tres import V0042StepTres

class TestV0042StepTres(unittest.TestCase):
    """V0042StepTres unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042StepTres:
        """Test V0042StepTres
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042StepTres`
        """
        model = V0042StepTres()
        if include_optional:
            return V0042StepTres(
                requested = openapi_client.models.v0_0_42_step_tres_requested.v0_0_42_step_tres_requested(
                    max = [
                        openapi_client.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    min = [
                        openapi_client.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    average = [
                        
                        ], 
                    total = [
                        
                        ], ),
                consumed = openapi_client.models.v0_0_42_step_tres_consumed.v0_0_42_step_tres_consumed(
                    max = [
                        openapi_client.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    min = [
                        openapi_client.models.v0/0/42_tres.v0.0.42_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    average = [
                        
                        ], 
                    total = [
                        
                        ], ),
                allocated = [
                    openapi_client.models.v0/0/42_tres.v0.0.42_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ]
            )
        else:
            return V0042StepTres(
        )
        """

    def testV0042StepTres(self):
        """Test V0042StepTres"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
