# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_node import V0043Node

class TestV0043Node(unittest.TestCase):
    """V0043Node unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043Node:
        """Test V0043Node
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043Node`
        """
        model = V0043Node()
        if include_optional:
            return V0043Node(
                architecture = '',
                burstbuffer_network_address = '',
                boards = 56,
                boot_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tls_cert_last_renewal = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cert_flags = [
                    'TOKEN_SET'
                    ],
                cluster_name = '',
                cores = 56,
                specialized_cores = 56,
                cpu_binding = 56,
                cpu_load = 56,
                free_mem = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpus = 56,
                effective_cpus = 56,
                specialized_cpus = '',
                energy = openapi_client.models.v0/0/43_acct_gather_energy.v0.0.43_acct_gather_energy(
                    average_watts = 56, 
                    base_consumed_energy = 56, 
                    consumed_energy = 56, 
                    current_watts = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    previous_consumed_energy = 56, 
                    last_collected = 56, ),
                external_sensors = openapi_client.models.external_sensors.external_sensors(),
                extra = '',
                power = openapi_client.models.power.power(),
                features = [
                    ''
                    ],
                active_features = [
                    ''
                    ],
                gpu_spec = '',
                gres = '',
                gres_drained = '',
                gres_used = '',
                instance_id = '',
                instance_type = '',
                last_busy = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                mcs_label = '',
                specialized_memory = 56,
                name = '',
                next_state_after_reboot = [
                    'INVALID'
                    ],
                address = '',
                hostname = '',
                state = [
                    'INVALID'
                    ],
                operating_system = '',
                owner = '',
                partitions = [
                    ''
                    ],
                port = 56,
                real_memory = 56,
                res_cores_per_gpu = 56,
                comment = '',
                reason = '',
                reason_changed_at = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                reason_set_by_user = '',
                resume_after = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                reservation = '',
                alloc_memory = 56,
                alloc_cpus = 56,
                alloc_idle_cpus = 56,
                tres_used = '',
                tres_weighted = 1.337,
                slurmd_start_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                sockets = 56,
                threads = 56,
                temporary_disk = 56,
                weight = 56,
                topology = '',
                tres = '',
                version = ''
            )
        else:
            return V0043Node(
        )
        """

    def testV0043Node(self):
        """Test V0043Node"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
