# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_partition_info_cpus import V0043PartitionInfoCpus

class TestV0043PartitionInfoCpus(unittest.TestCase):
    """V0043PartitionInfoCpus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043PartitionInfoCpus:
        """Test V0043PartitionInfoCpus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043PartitionInfoCpus`
        """
        model = V0043PartitionInfoCpus()
        if include_optional:
            return V0043PartitionInfoCpus(
                task_binding = 56,
                total = 56
            )
        else:
            return V0043PartitionInfoCpus(
        )
        """

    def testV0043PartitionInfoCpus(self):
        """Test V0043PartitionInfoCpus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
