# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_stats_rec import V0043StatsRec

class TestV0043StatsRec(unittest.TestCase):
    """V0043StatsRec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StatsRec:
        """Test V0043StatsRec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StatsRec`
        """
        model = V0043StatsRec()
        if include_optional:
            return V0043StatsRec(
                time_start = 56,
                rollups = openapi_client.models.v0/0/43_rollup_stats.v0.0.43_rollup_stats(
                    hourly = openapi_client.models.v0_0_43_rollup_stats_hourly.v0_0_43_rollup_stats_hourly(
                        count = 56, 
                        last_run = 56, 
                        duration = openapi_client.models.v0_0_42_rollup_stats_hourly_duration.v0_0_42_rollup_stats_hourly_duration(
                            last = 56, 
                            max = 56, 
                            time = 56, ), ), 
                    daily = openapi_client.models.v0_0_43_rollup_stats_daily.v0_0_43_rollup_stats_daily(
                        count = 56, 
                        last_run = 56, ), 
                    monthly = openapi_client.models.v0_0_43_rollup_stats_monthly.v0_0_43_rollup_stats_monthly(
                        count = 56, 
                        last_run = 56, ), ),
                rpcs = [
                    openapi_client.models.v0/0/43_stats_rpc.v0.0.43_stats_rpc(
                        rpc = '', 
                        count = 56, 
                        time = openapi_client.models.v0_0_42_stats_rpc_time.v0_0_42_stats_rpc_time(
                            average = 56, 
                            total = 56, ), )
                    ],
                users = [
                    openapi_client.models.v0/0/43_stats_user.v0.0.43_stats_user(
                        user = '', 
                        count = 56, 
                        time = openapi_client.models.v0_0_42_stats_rpc_time.v0_0_42_stats_rpc_time(
                            average = 56, 
                            total = 56, ), )
                    ]
            )
        else:
            return V0043StatsRec(
        )
        """

    def testV0043StatsRec(self):
        """Test V0043StatsRec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
