# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_step_step import V0043StepStep

class TestV0043StepStep(unittest.TestCase):
    """V0043StepStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StepStep:
        """Test V0043StepStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StepStep`
        """
        model = V0043StepStep()
        if include_optional:
            return V0043StepStep(
                id = '',
                name = '',
                stderr = '',
                stdin = '',
                stdout = '',
                stderr_expanded = '',
                stdin_expanded = '',
                stdout_expanded = ''
            )
        else:
            return V0043StepStep(
        )
        """

    def testV0043StepStep(self):
        """Test V0043StepStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
