# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0040_step_time import V0040StepTime

class TestV0040StepTime(unittest.TestCase):
    """V0040StepTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040StepTime:
        """Test V0040StepTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040StepTime`
        """
        model = V0040StepTime()
        if include_optional:
            return V0040StepTime(
                elapsed = 56,
                end = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                start = openapi_client.models.v0/0/40_uint64_no_val.v0.0.40_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                suspended = 56,
                system = openapi_client.models.v0_0_42_step_time_system.v0_0_42_step_time_system(
                    seconds = 56, 
                    microseconds = 56, ),
                total = openapi_client.models.v0_0_42_step_time_total.v0_0_42_step_time_total(
                    seconds = 56, 
                    microseconds = 56, ),
                user = openapi_client.models.v0_0_42_step_time_user.v0_0_42_step_time_user(
                    seconds = 56, 
                    microseconds = 56, )
            )
        else:
            return V0040StepTime(
        )
        """

    def testV0040StepTime(self):
        """Test V0040StepTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
