# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0040_users_add_cond import V0040UsersAddCond

class TestV0040UsersAddCond(unittest.TestCase):
    """V0040UsersAddCond unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040UsersAddCond:
        """Test V0040UsersAddCond
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040UsersAddCond`
        """
        model = V0040UsersAddCond()
        if include_optional:
            return V0040UsersAddCond(
                accounts = [
                    ''
                    ],
                association = openapi_client.models.v0/0/40_assoc_rec_set.v0.0.40_assoc_rec_set(
                    comment = '', 
                    defaultqos = '', 
                    grpjobs = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    grpjobsaccrue = openapi_client.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    grpsubmitjobs = , 
                    grptres = [
                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    grptresmins = [
                        openapi_client.models.v0/0/40_tres.v0.0.40_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    grptresrunmins = , 
                    grpwall = , 
                    maxjobs = , 
                    maxjobsaccrue = , 
                    maxsubmitjobs = , 
                    maxtresminsperjob = , 
                    maxtresrunmins = , 
                    maxtresperjob = , 
                    maxtrespernode = , 
                    maxwalldurationperjob = , 
                    minpriothresh = , 
                    parent = '', 
                    priority = , 
                    qoslevel = [
                        ''
                        ], 
                    fairshare = 56, ),
                clusters = [
                    ''
                    ],
                partitions = [
                    ''
                    ],
                users = [
                    ''
                    ],
                wckeys = [
                    ''
                    ]
            )
        else:
            return V0040UsersAddCond(
                users = [
                    ''
                    ],
        )
        """

    def testV0040UsersAddCond(self):
        """Test V0040UsersAddCond"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
