# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_openapi_reservation_mod_resp import V0043OpenapiReservationModResp

class TestV0043OpenapiReservationModResp(unittest.TestCase):
    """V0043OpenapiReservationModResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiReservationModResp:
        """Test V0043OpenapiReservationModResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiReservationModResp`
        """
        model = V0043OpenapiReservationModResp()
        if include_optional:
            return V0043OpenapiReservationModResp(
                reservations = [
                    openapi_client.models.v0/0/43_reservation_desc_msg.v0.0.43_reservation_desc_msg(
                        accounts = [
                            ''
                            ], 
                        burst_buffer = '', 
                        comment = '', 
                        core_count = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        duration = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        end_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        features = '', 
                        flags = [
                            'MAINT'
                            ], 
                        groups = [
                            ''
                            ], 
                        licenses = , 
                        max_start_delay = , 
                        name = '', 
                        node_count = , 
                        node_list = [
                            ''
                            ], 
                        partition = '', 
                        purge_completed = openapi_client.models.v0_0_43_reservation_info_purge_completed.v0_0_43_reservation_info_purge_completed(
                            time = , ), 
                        start_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = [
                            openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        users = , )
                    ],
                meta = openapi_client.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiReservationModResp(
                reservations = [
                    openapi_client.models.v0/0/43_reservation_desc_msg.v0.0.43_reservation_desc_msg(
                        accounts = [
                            ''
                            ], 
                        burst_buffer = '', 
                        comment = '', 
                        core_count = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        duration = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        end_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        features = '', 
                        flags = [
                            'MAINT'
                            ], 
                        groups = [
                            ''
                            ], 
                        licenses = , 
                        max_start_delay = , 
                        name = '', 
                        node_count = , 
                        node_list = [
                            ''
                            ], 
                        partition = '', 
                        purge_completed = openapi_client.models.v0_0_43_reservation_info_purge_completed.v0_0_43_reservation_info_purge_completed(
                            time = , ), 
                        start_time = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = [
                            openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        users = , )
                    ],
        )
        """

    def testV0043OpenapiReservationModResp(self):
        """Test V0043OpenapiReservationModResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
