# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_rollup_stats_monthly import V0043RollupStatsMonthly

class TestV0043RollupStatsMonthly(unittest.TestCase):
    """V0043RollupStatsMonthly unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043RollupStatsMonthly:
        """Test V0043RollupStatsMonthly
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043RollupStatsMonthly`
        """
        model = V0043RollupStatsMonthly()
        if include_optional:
            return V0043RollupStatsMonthly(
                count = 56,
                last_run = 56,
                duration = openapi_client.models.v0_0_42_rollup_stats_monthly_duration.v0_0_42_rollup_stats_monthly_duration(
                    last = 56, 
                    max = 56, 
                    time = 56, )
            )
        else:
            return V0043RollupStatsMonthly(
        )
        """

    def testV0043RollupStatsMonthly(self):
        """Test V0043RollupStatsMonthly"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
