# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_partition_info_qos import V0043PartitionInfoQos

class TestV0043PartitionInfoQos(unittest.TestCase):
    """V0043PartitionInfoQos unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043PartitionInfoQos:
        """Test V0043PartitionInfoQos
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043PartitionInfoQos`
        """
        model = V0043PartitionInfoQos()
        if include_optional:
            return V0043PartitionInfoQos(
                allowed = '',
                deny = '',
                assigned = ''
            )
        else:
            return V0043PartitionInfoQos(
        )
        """

    def testV0043PartitionInfoQos(self):
        """Test V0043PartitionInfoQos"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
