# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_openapi_accounts_resp import V0043OpenapiAccountsResp

class TestV0043OpenapiAccountsResp(unittest.TestCase):
    """V0043OpenapiAccountsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiAccountsResp:
        """Test V0043OpenapiAccountsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiAccountsResp`
        """
        model = V0043OpenapiAccountsResp()
        if include_optional:
            return V0043OpenapiAccountsResp(
                accounts = [
                    openapi_client.models.v0/0/43_account.v0.0.43_account(
                        associations = [
                            openapi_client.models.v0/0/43_assoc_short.v0.0.43_assoc_short(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            openapi_client.models.v0/0/43_coord.v0.0.43_coord(
                                name = '', 
                                direct = True, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
                meta = openapi_client.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiAccountsResp(
                accounts = [
                    openapi_client.models.v0/0/43_account.v0.0.43_account(
                        associations = [
                            openapi_client.models.v0/0/43_assoc_short.v0.0.43_assoc_short(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            openapi_client.models.v0/0/43_coord.v0.0.43_coord(
                                name = '', 
                                direct = True, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
        )
        """

    def testV0043OpenapiAccountsResp(self):
        """Test V0043OpenapiAccountsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
