# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_job_res import V0043JobRes

class TestV0043JobRes(unittest.TestCase):
    """V0043JobRes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043JobRes:
        """Test V0043JobRes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043JobRes`
        """
        model = V0043JobRes()
        if include_optional:
            return V0043JobRes(
                select_type = [
                    'CPU'
                    ],
                nodes = openapi_client.models.v0_0_43_job_res_nodes.v0_0_43_job_res_nodes(
                    count = 56, 
                    select_type = [
                        'AVAILABLE'
                        ], 
                    list = '', 
                    whole = True, 
                    allocation = [
                        openapi_client.models.v0/0/43_job_res_node.v0.0.43_job_res_node(
                            index = 56, 
                            name = '', 
                            cpus = openapi_client.models.v0_0_42_job_res_node_cpus.v0_0_42_job_res_node_cpus(
                                count = 56, 
                                used = 56, ), 
                            memory = openapi_client.models.v0_0_42_job_res_node_memory.v0_0_42_job_res_node_memory(
                                used = 56, 
                                allocated = 56, ), 
                            sockets = [
                                openapi_client.models.v0/0/43_job_res_socket.v0.0.43_job_res_socket(
                                    index = 56, 
                                    cores = [
                                        openapi_client.models.v0/0/43_job_res_core.v0.0.43_job_res_core(
                                            index = 56, 
                                            status = [
                                                'INVALID'
                                                ], )
                                        ], )
                                ], )
                        ], ),
                cpus = 56,
                threads_per_core = openapi_client.models.v0/0/43_uint16_no_val_struct.v0.0.43_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0043JobRes(
                select_type = [
                    'CPU'
                    ],
                cpus = 56,
                threads_per_core = openapi_client.models.v0/0/43_uint16_no_val_struct.v0.0.43_uint16_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0043JobRes(self):
        """Test V0043JobRes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
