# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0042_openapi_shares_resp import V0042OpenapiSharesResp

class TestV0042OpenapiSharesResp(unittest.TestCase):
    """V0042OpenapiSharesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042OpenapiSharesResp:
        """Test V0042OpenapiSharesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042OpenapiSharesResp`
        """
        model = V0042OpenapiSharesResp()
        if include_optional:
            return V0042OpenapiSharesResp(
                shares = openapi_client.models.v0/0/42_shares_resp_msg.v0.0.42_shares_resp_msg(
                    shares = [
                        openapi_client.models.v0/0/42_assoc_shares_obj_wrap.v0.0.42_assoc_shares_obj_wrap(
                            id = 56, 
                            cluster = '', 
                            name = '', 
                            parent = '', 
                            partition = '', 
                            shares_normalized = openapi_client.models.v0/0/42_float64_no_val_struct.v0.0.42_float64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            tres = openapi_client.models.v0_0_42_assoc_shares_obj_wrap_tres.v0_0_42_assoc_shares_obj_wrap_tres(
                                run_seconds = [
                                    openapi_client.models.v0/0/42_shares_uint64_tres.v0.0.42_shares_uint64_tres(
                                        name = '', 
                                        value = openapi_client.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), )
                                    ], 
                                group_minutes = [
                                    openapi_client.models.v0/0/42_shares_uint64_tres.v0.0.42_shares_uint64_tres(
                                        name = '', )
                                    ], 
                                usage = [
                                    openapi_client.models.v0/0/42_shares_float128_tres.v0.0.42_shares_float128_tres(
                                        name = '', )
                                    ], ), 
                            effective_usage = openapi_client.models.v0/0/42_float64_no_val_struct.v0.0.42_float64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            usage_normalized = , 
                            usage = 56, 
                            fairshare = openapi_client.models.v0_0_42_assoc_shares_obj_wrap_fairshare.v0_0_42_assoc_shares_obj_wrap_fairshare(
                                factor = , 
                                level = , ), 
                            type = [
                                'USER'
                                ], )
                        ], 
                    total_shares = 56, ),
                meta = openapi_client.models.v0/0/42_openapi_meta.v0.0.42_openapi_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0/0/42_openapi_error.v0.0.42_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0/0/42_openapi_warning.v0.0.42_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0042OpenapiSharesResp(
                shares = openapi_client.models.v0/0/42_shares_resp_msg.v0.0.42_shares_resp_msg(
                    shares = [
                        openapi_client.models.v0/0/42_assoc_shares_obj_wrap.v0.0.42_assoc_shares_obj_wrap(
                            id = 56, 
                            cluster = '', 
                            name = '', 
                            parent = '', 
                            partition = '', 
                            shares_normalized = openapi_client.models.v0/0/42_float64_no_val_struct.v0.0.42_float64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            tres = openapi_client.models.v0_0_42_assoc_shares_obj_wrap_tres.v0_0_42_assoc_shares_obj_wrap_tres(
                                run_seconds = [
                                    openapi_client.models.v0/0/42_shares_uint64_tres.v0.0.42_shares_uint64_tres(
                                        name = '', 
                                        value = openapi_client.models.v0/0/42_uint64_no_val_struct.v0.0.42_uint64_no_val_struct(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), )
                                    ], 
                                group_minutes = [
                                    openapi_client.models.v0/0/42_shares_uint64_tres.v0.0.42_shares_uint64_tres(
                                        name = '', )
                                    ], 
                                usage = [
                                    openapi_client.models.v0/0/42_shares_float128_tres.v0.0.42_shares_float128_tres(
                                        name = '', )
                                    ], ), 
                            effective_usage = openapi_client.models.v0/0/42_float64_no_val_struct.v0.0.42_float64_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            usage_normalized = , 
                            usage = 56, 
                            fairshare = openapi_client.models.v0_0_42_assoc_shares_obj_wrap_fairshare.v0_0_42_assoc_shares_obj_wrap_fairshare(
                                factor = , 
                                level = , ), 
                            type = [
                                'USER'
                                ], )
                        ], 
                    total_shares = 56, ),
        )
        """

    def testV0042OpenapiSharesResp(self):
        """Test V0042OpenapiSharesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
