# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_user import V0043User

class TestV0043User(unittest.TestCase):
    """V0043User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043User:
        """Test V0043User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043User`
        """
        model = V0043User()
        if include_optional:
            return V0043User(
                administrator_level = [
                    'Not Set'
                    ],
                associations = [
                    openapi_client.models.v0/0/43_assoc_short.v0.0.43_assoc_short(
                        account = '', 
                        cluster = '', 
                        partition = '', 
                        user = '', 
                        id = 56, )
                    ],
                coordinators = [
                    openapi_client.models.v0/0/43_coord.v0.0.43_coord(
                        name = '', 
                        direct = True, )
                    ],
                default = openapi_client.models.v0_0_42_user_default.v0_0_42_user_default(
                    account = '', 
                    wckey = '', ),
                flags = [
                    'NONE'
                    ],
                name = '',
                old_name = '',
                wckeys = [
                    openapi_client.models.v0/0/43_wckey.v0.0.43_wckey(
                        accounting = [
                            openapi_client.models.v0/0/43_accounting.v0.0.43_accounting(
                                allocated = openapi_client.models.v0_0_42_accounting_allocated.v0_0_42_accounting_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                id_alt = 56, 
                                start = 56, 
                                tres = openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ]
            )
        else:
            return V0043User(
                name = '',
        )
        """

    def testV0043User(self):
        """Test V0043User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
