# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_job_desc_msg_rlimits import V0043JobDescMsgRlimits

class TestV0043JobDescMsgRlimits(unittest.TestCase):
    """V0043JobDescMsgRlimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043JobDescMsgRlimits:
        """Test V0043JobDescMsgRlimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043JobDescMsgRlimits`
        """
        model = V0043JobDescMsgRlimits()
        if include_optional:
            return V0043JobDescMsgRlimits(
                cpu = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                fsize = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                data = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                stack = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                core = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                rss = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                nproc = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                nofile = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                memlock = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                var_as = openapi_client.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0043JobDescMsgRlimits(
        )
        """

    def testV0043JobDescMsgRlimits(self):
        """Test V0043JobDescMsgRlimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
