# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner import V0041OpenapiSlurmdbdJobsRespJobsInner

class TestV0041OpenapiSlurmdbdJobsRespJobsInner(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInner:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInner`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInner()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInner(
                account = '',
                comment = openapi_client.models.v0_0_42_job_comment.v0_0_42_job_comment(
                    administrator = '', 
                    job = '', 
                    system = '', ),
                allocation_nodes = 56,
                array = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array(
                    job_id = 56, 
                    limits = openapi_client.models.v0_0_42_job_array_limits.v0_0_42_job_array_limits(
                        max = openapi_client.models.v0_0_42_job_array_limits_max.v0_0_42_job_array_limits_max(
                            running = openapi_client.models.v0_0_42_job_array_limits_max_running.v0_0_42_job_array_limits_max_running(
                                tasks = 56, ), ), ), 
                    task_id = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_array_task_id(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    task = '', ),
                association = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_association(
                    account = '', 
                    cluster = '', 
                    partition = '', 
                    user = '', 
                    id = 56, ),
                block = '',
                cluster = '',
                constraints = '',
                container = '',
                derived_exit_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code(
                    status = [
                        'INVALID'
                        ], 
                    return_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal(
                        id = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time(
                    elapsed = 56, 
                    eligible = 56, 
                    end = 56, 
                    planned = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    start = 56, 
                    submission = 56, 
                    suspended = 56, 
                    system = openapi_client.models.v0_0_42_job_time_system.v0_0_42_job_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    limit = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_limit.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_limit(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    total = openapi_client.models.v0_0_42_job_time_total.v0_0_42_job_time_total(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = openapi_client.models.v0_0_42_job_time_user.v0_0_42_job_time_user(
                        seconds = 56, 
                        microseconds = 56, ), ),
                exit_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code(
                    status = [
                        'INVALID'
                        ], 
                    return_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal(
                        id = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                extra = '',
                failed_node = '',
                flags = [
                    'NONE'
                    ],
                group = '',
                het = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het(
                    job_id = 56, 
                    job_offset = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het_job_offset.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_het_job_offset(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                job_id = 56,
                name = '',
                licenses = '',
                mcs = openapi_client.models.v0_0_42_job_mcs.v0_0_42_job_mcs(
                    label = '', ),
                nodes = '',
                partition = '',
                hold = True,
                priority = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_priority(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                qos = '',
                required = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required(
                    cpus = 56, 
                    memory_per_cpu = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_cpu(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    memory_per_node = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_node.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_required_memory_per_node(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                kill_request_user = '',
                reservation = openapi_client.models.v0_0_42_job_reservation.v0_0_42_job_reservation(
                    id = 56, 
                    name = '', ),
                script = '',
                stdin_expanded = '',
                stdout_expanded = '',
                stderr_expanded = '',
                stdout = '',
                stderr = '',
                stdin = '',
                state = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_state(
                    current = [
                        'PENDING'
                        ], 
                    reason = '', ),
                steps = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner(
                        time = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time(
                            elapsed = 56, 
                            end = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_end(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            start = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_start(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            suspended = 56, 
                            system = openapi_client.models.v0_0_42_step_time_system.v0_0_42_step_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            total = openapi_client.models.v0_0_42_step_time_total.v0_0_42_step_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = openapi_client.models.v0_0_42_step_time_user.v0_0_42_step_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_exit_code(
                            status = [
                                'INVALID'
                                ], 
                            return_code = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_return_code(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            signal = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal(
                                id = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_derived_exit_code_signal_id(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                name = '', ), ), 
                        nodes = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_nodes(
                            count = 56, 
                            range = '', 
                            list = [
                                ''
                                ], ), 
                        tasks = openapi_client.models.v0_0_42_step_tasks.v0_0_42_step_tasks(
                            count = 56, ), 
                        pid = '', 
                        cpu = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU(
                            requested_frequency = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency(
                                min = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_min.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency_min(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), 
                                max = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_cpu_requested_frequency_max.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_CPU_requested_frequency_max(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), 
                            governor = '', ), 
                        kill_request_user = '', 
                        state = [
                            'PENDING'
                            ], 
                        statistics = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics(
                            energy = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy(
                                consumed = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_energy_consumed(
                                    set = True, 
                                    infinite = True, 
                                    number = 56, ), ), ), 
                        step = openapi_client.models.v0_0_42_step_step.v0_0_42_step_step(
                            name = '', ), 
                        task = openapi_client.models.v0_0_42_step_task.v0_0_42_step_task(
                            distribution = '', ), 
                        tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres(
                            requested = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested(
                                average = [
                                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                        type = '', 
                                        name = '', 
                                        count = 56, )
                                    ], ), 
                            allocated = [
                                openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                                    type = '', 
                                    name = '', 
                                    count = 56, )
                                ], ), )
                    ],
                submit_line = '',
                tres = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres(
                    allocated = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    requested = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_tres_requested_max_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                used_gres = '',
                user = '',
                wckey = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_wckey(
                    wckey = '', 
                    flags = [
                        'ASSIGNED_DEFAULT'
                        ], ),
                working_directory = ''
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInner(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInner(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
