# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0041_openapi_slurmdbd_stats_resp import V0041OpenapiSlurmdbdStatsResp

class TestV0041OpenapiSlurmdbdStatsResp(unittest.TestCase):
    """V0041OpenapiSlurmdbdStatsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdStatsResp:
        """Test V0041OpenapiSlurmdbdStatsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdStatsResp`
        """
        model = V0041OpenapiSlurmdbdStatsResp()
        if include_optional:
            return V0041OpenapiSlurmdbdStatsResp(
                statistics = openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics.v0_0_41_openapi_slurmdbd_stats_resp_statistics(
                    time_start = 56, 
                    rollups = openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups(
                        hourly = openapi_client.models.v0_0_42_rollup_stats_hourly.v0_0_42_rollup_stats_hourly(
                            count = 56, 
                            last_run = 56, 
                            duration = openapi_client.models.v0_0_42_rollup_stats_hourly_duration.v0_0_42_rollup_stats_hourly_duration(
                                last = 56, 
                                max = 56, 
                                time = 56, ), ), 
                        daily = openapi_client.models.v0_0_42_rollup_stats_daily.v0_0_42_rollup_stats_daily(
                            count = 56, 
                            last_run = 56, ), 
                        monthly = openapi_client.models.v0_0_42_rollup_stats_monthly.v0_0_42_rollup_stats_monthly(
                            count = 56, 
                            last_run = 56, ), ), 
                    rpcs = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rpcs_inner.v0_0_41_openapi_slurmdbd_stats_resp_statistics_RPCs_inner(
                            rpc = '', 
                            count = 56, 
                            time = openapi_client.models.v0_0_42_stats_rpc_time.v0_0_42_stats_rpc_time(
                                average = 56, 
                                total = 56, ), )
                        ], 
                    users = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_users_inner.v0_0_41_openapi_slurmdbd_stats_resp_statistics_users_inner(
                            user = '', 
                            count = 56, )
                        ], ),
                meta = openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_meta.v0_0_41_openapi_slurmdbd_jobs_resp_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner.v0_0_41_openapi_slurmdbd_jobs_resp_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner.v0_0_41_openapi_slurmdbd_jobs_resp_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiSlurmdbdStatsResp(
                statistics = openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics.v0_0_41_openapi_slurmdbd_stats_resp_statistics(
                    time_start = 56, 
                    rollups = openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups(
                        hourly = openapi_client.models.v0_0_42_rollup_stats_hourly.v0_0_42_rollup_stats_hourly(
                            count = 56, 
                            last_run = 56, 
                            duration = openapi_client.models.v0_0_42_rollup_stats_hourly_duration.v0_0_42_rollup_stats_hourly_duration(
                                last = 56, 
                                max = 56, 
                                time = 56, ), ), 
                        daily = openapi_client.models.v0_0_42_rollup_stats_daily.v0_0_42_rollup_stats_daily(
                            count = 56, 
                            last_run = 56, ), 
                        monthly = openapi_client.models.v0_0_42_rollup_stats_monthly.v0_0_42_rollup_stats_monthly(
                            count = 56, 
                            last_run = 56, ), ), 
                    rpcs = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rpcs_inner.v0_0_41_openapi_slurmdbd_stats_resp_statistics_RPCs_inner(
                            rpc = '', 
                            count = 56, 
                            time = openapi_client.models.v0_0_42_stats_rpc_time.v0_0_42_stats_rpc_time(
                                average = 56, 
                                total = 56, ), )
                        ], 
                    users = [
                        openapi_client.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_users_inner.v0_0_41_openapi_slurmdbd_stats_resp_statistics_users_inner(
                            user = '', 
                            count = 56, )
                        ], ),
        )
        """

    def testV0041OpenapiSlurmdbdStatsResp(self):
        """Test V0041OpenapiSlurmdbdStatsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
