# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_openapi_accounts_add_cond_resp import V0043OpenapiAccountsAddCondResp

class TestV0043OpenapiAccountsAddCondResp(unittest.TestCase):
    """V0043OpenapiAccountsAddCondResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiAccountsAddCondResp:
        """Test V0043OpenapiAccountsAddCondResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiAccountsAddCondResp`
        """
        model = V0043OpenapiAccountsAddCondResp()
        if include_optional:
            return V0043OpenapiAccountsAddCondResp(
                association_condition = openapi_client.models.v0/0/43_accounts_add_cond.v0.0.43_accounts_add_cond(
                    accounts = [
                        ''
                        ], 
                    association = openapi_client.models.v0/0/43_assoc_rec_set.v0.0.43_assoc_rec_set(
                        comment = '', 
                        defaultqos = '', 
                        grpjobs = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        grpjobsaccrue = openapi_client.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        grpsubmitjobs = , 
                        grptres = [
                            openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        grptresmins = [
                            openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        grptresrunmins = , 
                        grpwall = , 
                        maxjobs = , 
                        maxjobsaccrue = , 
                        maxsubmitjobs = , 
                        maxtresminsperjob = , 
                        maxtresrunmins = , 
                        maxtresperjob = , 
                        maxtrespernode = , 
                        maxwalldurationperjob = , 
                        minpriothresh = , 
                        parent = '', 
                        priority = , 
                        qoslevel = [
                            ''
                            ], 
                        fairshare = 56, ), 
                    clusters = [
                        ''
                        ], ),
                account = openapi_client.models.v0/0/43_account_short.v0.0.43_account_short(
                    description = '', 
                    organization = '', ),
                meta = openapi_client.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiAccountsAddCondResp(
        )
        """

    def testV0043OpenapiAccountsAddCondResp(self):
        """Test V0043OpenapiAccountsAddCondResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
