# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_cluster_rec import V0043ClusterRec

class TestV0043ClusterRec(unittest.TestCase):
    """V0043ClusterRec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043ClusterRec:
        """Test V0043ClusterRec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043ClusterRec`
        """
        model = V0043ClusterRec()
        if include_optional:
            return V0043ClusterRec(
                controller = openapi_client.models.v0_0_42_cluster_rec_controller.v0_0_42_cluster_rec_controller(
                    host = '', 
                    port = 56, ),
                flags = [
                    'DELETED'
                    ],
                name = '',
                nodes = '',
                select_plugin = '',
                associations = openapi_client.models.v0_0_43_cluster_rec_associations.v0_0_43_cluster_rec_associations(
                    root = openapi_client.models.v0/0/43_assoc_short.v0.0.43_assoc_short(
                        account = '', 
                        cluster = '', 
                        partition = '', 
                        user = '', 
                        id = 56, ), ),
                rpc_version = 56,
                tres = [
                    openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ]
            )
        else:
            return V0043ClusterRec(
        )
        """

    def testV0043ClusterRec(self):
        """Test V0043ClusterRec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
