# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_openapi_wckey_resp import V0043OpenapiWckeyResp

class TestV0043OpenapiWckeyResp(unittest.TestCase):
    """V0043OpenapiWckeyResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043OpenapiWckeyResp:
        """Test V0043OpenapiWckeyResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043OpenapiWckeyResp`
        """
        model = V0043OpenapiWckeyResp()
        if include_optional:
            return V0043OpenapiWckeyResp(
                wckeys = [
                    openapi_client.models.v0/0/43_wckey.v0.0.43_wckey(
                        accounting = [
                            openapi_client.models.v0/0/43_accounting.v0.0.43_accounting(
                                allocated = openapi_client.models.v0_0_42_accounting_allocated.v0_0_42_accounting_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                id_alt = 56, 
                                start = 56, 
                                tres = openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
                meta = openapi_client.models.v0/0/43_openapi_meta.v0.0.43_openapi_meta(
                    plugin = openapi_client.models.v0_0_42_openapi_meta_plugin.v0_0_42_openapi_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = openapi_client.models.v0_0_42_openapi_meta_client.v0_0_42_openapi_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = openapi_client.models.v0_0_42_openapi_meta_slurm.v0_0_42_openapi_meta_slurm(
                        version = openapi_client.models.v0_0_42_openapi_meta_slurm_version.v0_0_42_openapi_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    openapi_client.models.v0/0/43_openapi_error.v0.0.43_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    openapi_client.models.v0/0/43_openapi_warning.v0.0.43_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0043OpenapiWckeyResp(
                wckeys = [
                    openapi_client.models.v0/0/43_wckey.v0.0.43_wckey(
                        accounting = [
                            openapi_client.models.v0/0/43_accounting.v0.0.43_accounting(
                                allocated = openapi_client.models.v0_0_42_accounting_allocated.v0_0_42_accounting_allocated(
                                    seconds = 56, ), 
                                id = 56, 
                                id_alt = 56, 
                                start = 56, 
                                tres = openapi_client.models.v0/0/43_tres.v0.0.43_tres(
                                    type = '', 
                                    name = '', 
                                    id = 56, 
                                    count = 56, ), )
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
        )
        """

    def testV0043OpenapiWckeyResp(self):
        """Test V0043OpenapiWckeyResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
