# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.05.0
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0043_partition_info_groups import V0043PartitionInfoGroups

class TestV0043PartitionInfoGroups(unittest.TestCase):
    """V0043PartitionInfoGroups unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043PartitionInfoGroups:
        """Test V0043PartitionInfoGroups
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043PartitionInfoGroups`
        """
        model = V0043PartitionInfoGroups()
        if include_optional:
            return V0043PartitionInfoGroups(
                allowed = ''
            )
        else:
            return V0043PartitionInfoGroups(
        )
        """

    def testV0043PartitionInfoGroups(self):
        """Test V0043PartitionInfoGroups"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
