qpus:
  ornl-iqm-20q:
    provider: iqm
    provider-device-id: default
    url: https://qccsw.ccs.ornl.gov/
    credential-db: qpu-users.json
  fake-iqm-20q:
    provider: fake-iqm
    provider-device-id: fake-iqm-20q
  ibm-156-nh:
    provider: ibm
    provider-device-id: ibm_156_nh
    resource-type: IBMQiskitRuntimeService
    url: https://quantum.cloud.ibm.com/api/v1
    credential-db: qpu-users.json
    libraries:
      - qrmi
    preference: qrmi
    execution-owner: qrmi
    caps:
      run_circuit: [qrmi]
      get_task_timing: [qrmi]
      get_task_metadata: [qrmi]
  aws:
    provider: aws
    provider-device-id: aws
    url: https://braket.us-east-1.amazonaws.com
    credential-db: qpu-users.json
    libraries:
      - qdmi
    preference: qdmi
    execution-owner: qdmi
    caps:
      run_circuit: [qdmi]
      get_task_timing: [qdmi]
      get_task_metadata: [qdmi]
  aws-ionq-aria-1:
    provider: aws
    provider-device-id: arn:aws:braket:us-east-1::device/qpu/ionq/Aria-1
    url: https://braket.us-east-1.amazonaws.com
    credential-db: qpu-users.json
    libraries:
      - qdmi
    preference: qdmi
    execution-owner: qdmi
    caps:
      run_circuit: [qdmi]
      get_task_timing: [qdmi]
      get_task_metadata: [qdmi]
  aws-rigetti-ankaa:
    provider: aws
    provider-device-id: arn:aws:braket:us-west-1::device/qpu/rigetti/Ankaa-3
    url: https://braket.us-west-1.amazonaws.com
    credential-db: qpu-users.json
    libraries:
      - qdmi
    preference: qdmi
    execution-owner: qdmi
    caps:
      run_circuit: [qdmi]
      get_task_timing: [qdmi]
      get_task_metadata: [qdmi]
