services:
  - name: nwqsim
    credential-mode: no-secret
    module: svc_nwqsim_qpm
    load-modules: svc_nwqsim_qpm,api_launcher
    environment-modules:
      - libfabric
      - openmpi
      - nwqsim
    required-executables:
      - circuit_runner.nwqsim
    agent-prefix: qpm_nwqsim
    assigned-hosts: ${QFW_SIMULATOR_NODES}
    assigned-hosts-env: QFW_QPM_ASSIGNED_HOSTS
    listen-port: 8490
    telnet-port: 8491
    provider-launch:
      type: mpi
      wrapper: null

  - name: fake-iqm
    credential-mode: no-secret
    module: svc_fake_iqm_qpm
    load-modules: svc_fake_iqm_qpm,api_launcher
    agent-prefix: qpm_fake_iqm
    assigned-hosts: group1
    assigned-hosts-env: QFW_QPM_ASSIGNED_HOSTS
    device-id: fake-iqm-20q
    listen-port: 8590
    telnet-port: 8591
    provider-launch:
      type: internal

  - name: iqm-ornl-20q
    credential-mode: required
    module: svc_iqm_qpm
    load-modules: svc_iqm_qpm,api_launcher
    agent-prefix: qpm_iqm
    device-id: ornl-iqm-20q
    listen-port: 8290
    telnet-port: 8291
    provider-launch:
      type: remote-api

  - name: shim-ornl-20q
    credential-mode: required
    module: svc_lib_qpm
    load-modules: svc_lib_qpm,api_launcher
    agent-prefix: qpm_shim
    device-id: ornl-iqm-20q
    listen-port: 8390
    telnet-port: 8391
    provider-launch:
      type: qrmi-qdmi

  - name: shim-ibm-156-nh
    credential-mode: required
    module: svc_lib_qpm
    load-modules: svc_lib_qpm,api_launcher
    agent-prefix: qpm_shim_ibm
    device-id: ibm-156-nh
    listen-port: 8690
    telnet-port: 8691
    provider-launch:
      type: qrmi-qdmi
